import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="antialised bg-slate-900">
        <div className="min-h-screen flex flex-col text-white bg-linear-to-br from-slate-800 via-slate-850 to-slate-900">
        <Navbar/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
